.github/workflows/codeql.yml

Created codeql.yml for CI code inspection to allow for continuous testing and inspection for the code base.
- Added `codeql.yml` workflow file.
No.
No.

Created `codeql.yml` for CI code inspection

---

solardoc/frontend/src/views/EditorView.vue

Making the preview structure, to improve the overview of the whole editor page.
- Added the structure for the future preview. However, it is not responsive yet.
No.

Improved structure for editor page

---

.mocharc.json
.nycrc.json
package.json
pnpm-lock.yaml
solardoc/frontend/package.json
solardoc/frontend/pnpm-lock.yaml
test/modules/asciidoc-renderer/setup.test.ts
test/web-bundle-test.html
tsconfig.json

Set up the testing environment for the Solardoc libraries, primarily at the moment `@solardoc/asciidoc-renderer`. 
Closes #49 
- Added test environment using `mocha` and `chai`.
- Add web-script HTML file `web-bundle-test.html`.
No.

Set up testing environment

---

.github/workflows/docker-build-and-publish.yml
.github/workflows/eslint.yml
README.adoc
docker-compose-prod.yaml
docker-compose.yaml
solardoc/asciidoc-renderer/src/presentation.ts
solardoc/asciidoc-renderer/src/renderer/targets/html/html-renderer-config.ts
solardoc/asciidoc-renderer/src/renderer/targets/html/html-renderer.ts
solardoc/asciidoc-renderer/src/renderer/targets/image/image-renderer.ts
solardoc/asciidoc-renderer/src/renderer/targets/pdf/node/node-pdf-renderer.ts
solardoc/asciidoc-renderer/src/renderer/targets/pdf/web/web-pdf-renderer.ts
solardoc/asciidoc-renderer/src/renderer/targets/target-renderer.ts
solardoc/frontend/Dockerfile
solardoc/frontend/src/assets/core/_dotdotdot.scss
solardoc/frontend/src/assets/core/_var.scss
solardoc/frontend/src/assets/main.scss
solardoc/frontend/src/components/editor/Editor.vue
solardoc/frontend/src/services/backend/api-service.ts
solardoc/frontend/src/services/backend/gen/backend-rest-service.ts
solardoc/frontend/src/stores/editor-content.ts
solardoc/frontend/src/stores/init-state.ts
solardoc/frontend/src/stores/preview-loading.ts
solardoc/frontend/src/views/EditorView.vue
solardoc/rest-api/Dockerfile
solardoc/rest-api/src/controllers/v1/render.controller.ts
solardoc/rest-api/src/controllers/v1/result.controller.ts
solardoc/rest-api/src/models/dto/render-presentation-rjs-html-dto.model.ts
solardoc/rest-api/src/services/render.service.ts
test/modules/asciidoc-renderer/html-renderer.test.ts

Integrated the preview frame into the editor using the render REST-API.
Closes #47 
- Implemented usage of the auto-generated REST client.
- Added automatic render when the user input changes (With a one second timeout to prevent constant requests/auto-ddos).
- Implemented loading "..." indicator.
No.

Integrated the preview frame into the editor using the render REST-API

---

solardoc/frontend/src/components/Navbar.vue
solardoc/frontend/src/plugins/constants.ts

Added version tag displaying the current release of Solardoc in the navigation bar.
- Added version tag displaying the current release of Solardoc in the navigation bar. This also is an `<a>`  tag, which points to the specified version on GitHub.
None.

Added version tag to Solardoc title in navigation bar

---

solardoc/frontend/src/views/EditorView.vue

Fixed type build bug in editor view.
- Fixed invalid type for timeout in frontend.
No.

Fixed type build bug in editor view

---

solardoc/frontend/src/assets/core/_var.scss
solardoc/frontend/src/components/slides-navigator/SlidePreview.vue
solardoc/frontend/src/components/slides-navigator/SlidesNavigator.vue
solardoc/frontend/src/components/sub-slides-navigator/SlideSubSlidePreview.vue
solardoc/frontend/src/components/sub-slides-navigator/SlideSubSlidesPreview.vue
solardoc/frontend/src/components/sub-slides-navigator/SubSlidesNavigator.vue
solardoc/frontend/src/stores/file-name.ts
solardoc/frontend/src/stores/preview-menu-slide-state.ts
solardoc/frontend/src/stores/preview-selected-slide.ts
solardoc/frontend/src/views/EditorView.vue

Fixed copy button not working in HTTP-only context (This is by using the deprecated browser API `document.execCommand()` which still work in HTTP mode)
- Fixed copy button not working in HTTP-only context by adding fallback unsafe copy.
None.

Fixed copy button not working in HTTP-only context

---

solardoc/frontend/src/components/channel-view/ChannelViewJoinConfirm.vue

Added a form for joining a channel by entering the channels password.
- Added password form
None.

Implemented password form for joining channels

---

solardoc/frontend/src/components/editor/channel-view/ChannelViewCreate.vue
solardoc/frontend/src/components/editor/channel-view/ChannelViewJoinConfirm.vue
solardoc/frontend/src/views/LoginView.vue
solardoc/frontend/src/views/SignupView.vue

…aviour for all forms
Fixed bug in the vueform forms in the frontend, which were throwing axios errors due to an incorrect configuration.
Closes #112
- Updated all Vueform forms and made sure that they are not using any endpoints, but rather relies on the frontend data validation.
None.

Fixed Vueform bug throwing axios error every time the form is submitted

---

solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue

A button was added for creating a new file by closing the currently opened file in the editor.
Closes #129 
- Added a button in the drop-down menu
None.

Implemented new file button which clears the current file and opens up a new local file

---

.github/workflows/elixir.yml

Added new workflow for testing the phoenix project.
- Added new workflow file `elixir.yml`.
None.

Created elixir.yml workflow

---

solardoc/frontend/src/App.vue
solardoc/frontend/src/assets/main.scss
solardoc/frontend/src/views/ShareURLView.vue

Fixed layout bug of footer being visible when main components are still loading.
Closes #148 
- Fixed main layout not filling up the space between the header and footer.
None.

Fixed layout bug of footer being visible when main components are still loading

---

solardoc/frontend/src/scripts/editor/monaco-config/dark-editor-theme.ts

Changed the color for headings in the editor to `#7966c4`, to make them more visible in the dark-mode.
Closes #164 
- Changed editor header color to `#7966c4`.
None.

Changed color for headings in the editor

---

solardoc/frontend/src/stores/current-file.ts

Fixed last modified not being updated with remote updates.
Closes #168 
- Added additional `setLastModified()` in `currentFileStore.applyOTrans()`.
None.

Fixed last modified not being updated with remote updates

---

solardoc/frontend/src/scripts/is-valid-path.ts
solardoc/frontend/src/views/LoginView.vue

Implemented `returnTo` query parameter which will after a successful login redirect to the given page.
Closes #110 
- Added new query parameter `returnTo` which will be used as the redirect target if the user logs in or is already logged in.
None.

Implemented `returnTo` query parameter which will after a successful login redirect to the given page

---

solardoc/frontend/src/components/profile-view/file-view/FilesList.vue
solardoc/frontend/src/components/profile-view/file-view/ProfileFileOverview.vue
solardoc/frontend/src/components/profile-view/file-view/SearchBar.vue

Added functionality to search bar.
Closes #143 
- Implemented search bar
None.

Implemented search bar functionality for file viewer in the profile page

---

solardoc/frontend/src/components/editor/SaveStateBadge.vue
solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
solardoc/frontend/src/components/profile-view/file-view/FilesList.vue
solardoc/frontend/src/components/profile-view/file-view/ProfileFileOverview.vue
solardoc/frontend/src/components/profile-view/file-view/SearchBar.vue
solardoc/frontend/src/scripts/editor/sds.ts
solardoc/frontend/src/scripts/is-valid-path.ts
solardoc/frontend/src/views/EditorView.vue
solardoc/frontend/src/views/LoginView.vue
solardoc/frontend/src/views/ShareURLView.vue

Fixed bug of user not being redirected to the editor after logging in to access a share URL.
Closes #162 
- Added redirect to `ShareURLView.vue` using the `returnTo` query parameter implemented by #179.
None.

Fixed bug of user not being redirected to the editor after logging in to access a share URL

---

solardoc/frontend/src/components/profile-view/file-view/SearchBar.vue
solardoc/frontend/src/views/LoginView.vue
solardoc/frontend/src/views/SignupView.vue

Fixed password manager field detection bugs in login & register forms.
Closes #185 
- Added additional metadata to the form fields to more clearly signalise their role in the form.
None.

Fixed password manager field detection bugs in login & register forms

---

solardoc/frontend/src/components/profile-view/file-view/FileCard.vue

Closes #153 
- Added call to the `closeEditorRemoteFileConnection()` function when deleting a file.
None.

Fixed file still present in the editor after being deleted bug

---

solardoc/phoenix-server/lib/solardoc_phoenix/accounts/user_notifier.ex
solardoc/phoenix-server/lib/solardoc_phoenix/files.ex
solardoc/phoenix-server/lib/solardoc_phoenix/files/file.ex
solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/files/file_controller.ex
solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/files/file_json.ex
solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/share_url/share_url_controller.ex
solardoc/phoenix-server/lib/solardoc_phoenix_web/endpoint.ex
solardoc/phoenix-server/lib/solardoc_phoenix_web/router.ex
solardoc/phoenix-server/mix.exs
solardoc/phoenix-server/package.json
solardoc/phoenix-server/priv/repo/migrations/20241010071604_add_global_bit_files.exs

Implemented global query backend for querying global files using a logged-in user.
Closes #211 
- Added global files backend using `~/v1/files/global`
- Added query functionality in module `Files`.
None.

Implemented global query backend for querying global files

---

solardoc/frontend/src/plugins/constants.ts

Adding a proper default page for the asciidoc file, so users get  a bit familar with asciidoc
Closes #217
- Changed the constant of default file content.
None.

Added default example page for the editor

---

solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
solardoc/phoenix-server/lib/solardoc_phoenix/permissions.ex
solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/files/file_permission_controller.ex

Fixed issue with creating a new file permission throwing a 500 due to a missing import
Closes #231 
- Added missing imports in Phoenix backend endpoint.
None.

Fixed error when creating a new file permission

---

solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
solardoc/frontend/src/components/editor/dropdown/share-url/ShareUrlCreate.vue

Added the option to change the file name in the file settings and save said change directly in there.
Closes #228 
- Added option to change file name in file settings tab
- Removed disabled tag for write access check-box in share url create view
None.

Added option to change file name in file settings tab

---

solardoc/frontend/src/components/home/HomeFeatureCard.vue
solardoc/frontend/src/views/HomeView.vue

Filled out the placeholders on the homepage.
- Filled out the placeholders on the homepage.
- Made the homepage separator slightly taller.
None.

Added proper feature cards on the homepage

---

solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/sub-slides-navigator/SlidesManagerSubSlidesNavigator.vue

Fixed phone subslides viewer slide index starting at 0 instead of 1.
Closes #268
- Fixed phone subslides viewer slide index starting at 0 instead of 1.
- Changed the smiley to a happy one.
None.

Fixed phone subslides viewer slide index starting at 0 instead of 1

---

solardoc/frontend/src/main.ts
solardoc/frontend/src/router/index.ts
solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel.ex
solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel_state.ex
solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/utf16_comp.ex

Fixed incorrect UTF16 handling and implemented a custom OT insert & delete algorithm to resolve inconsistencies that occurred between the client and backend due to the Unicode character mishandling and index inconsistencies.
Closes #281
- Added new compatibility layer `UTF16Comp` for UTF-16 character handling.
- Added new insert and delete operations using custom UTF-16 character indexing and slicing to resemble the JavaScript counterpart.
None.

Fixed incorrect UTF16 handling and implemented a custom OT insert & delete algorithm

---

solardoc/frontend/src/components/editor/SaveStateBadge.vue
solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
solardoc/frontend/src/components/navbar/Navbar.vue
solardoc/frontend/src/main.ts
solardoc/frontend/src/router/index.ts
solardoc/frontend/src/scripts/editor/editor.ts
solardoc/frontend/src/scripts/editor/upload.ts
solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
solardoc/frontend/src/services/render/gen/backend-rest-service.ts
solardoc/frontend/src/views/EditorView.vue

Fixed upload bug in save state upload button, which didn't correctly update the URL during an upload.
Closes #285
- Consolidated the upload mechanism into a unified function which uploads a file and correctly updates the URL or simply updates the file if it was already uploaded.
None.

Fixed upload bug in save state upload button

---

docker-compose.yaml

Removed `restart: always` from the development docker compose file to avoid automatic startup on boot. There is no need to have SolarDoc run on OS startup.
- Removed `restart: always` from development docker-compose file
None
No linked issues

Removed `restart: always` from docker compose
